dist: trusty
language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2
  - 2.1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yqq nano
  - gem install bundler
install:
  - bundle
script:
  - rake
  - bin/e2e