FROM ruby:2.2-alpine

RUN apk add --no-cache \
  git build-base \
  nano

WORKDIR /app

COPY Gemfile Gemfile.lock kommando.gemspec ./
COPY lib/kommando/version.rb ./lib/kommando/
RUN bundle install

COPY . .
ENTRYPOINT docker/entrypoint.sh
