FROM ruby:2.4.1
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y nano

WORKDIR /app

COPY Gemfile Gemfile.lock kommando.gemspec ./
COPY lib/kommando/version.rb ./lib/kommando/
RUN bundle install

COPY . .
RUN rake